SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT ;
SET NAMES utf8 ;
SET NAMES utf8mb4 ;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 ;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' ;

Data exporting was unselected.
SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') ;
SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) ;
SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT ;
